package com.algsyntax.jetpackcomposetodo.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a task in the ToDo application.
 *
 * @property id The unique identifier for the task. This field is auto-generated by the database.
 * @property title The title of the task.
 * @property description A brief description of the task.
 * @property isCompleted Indicates whether the task has been completed. Defaults to false.
 */
@Entity(tableName = "task_table")
data class Task(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val description: String,
    var isCompleted: Boolean = false
)